### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by Benjythebee** [FarazzShaikh/three-shader-baker#4]
I see in the readme
```
Lighting is baked from a single point of view ([0, 0, -1] looking towards [0, 0, 0]). This means specular highlights and reflections will not be accurate if the camera is dynamic. This is a limitation of texture baking in general.
```

I'm seeing exactly this issue on my baked texture. Do you have a trick to have light being uniform?

**Comment by FarazzShaikh** [comment]
This is a limitation of baking, you can only bake from one prespective and thus only bake specular that looks correct from one single prespective. 

Do you have anu refrences where this is possible? If so, woud love to take a look.

**Comment by Benjythebee** [comment]
I was hoping you had a trick, because [the demo](https://farazzshaikh.github.io/three-shader-baker/) doesn't seem to have an issue with lighting, maybe I'm blind

**Comment by FarazzShaikh** [comment]
@Benjythebee that demo does not use any specular lighting. Only diffuse. 

Any shader that depends on the camera position (such as specular highlights, roughness, metalness, normal mapping, fresnel, etc) will not look correct when baked unless your viewing camera matches the baking camera’s position and rotation exactly

Diffuse and unlit shaders that don’t depend on the camera will work. That is the main purpose of this library
